name: Update Statsbomb Data - Parquet
on:
  schedule:
    - cron: "59 7 * * *"
    #- cron: "0 0 30 12 1"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas
          python -m pip install pyarrow
          python -m pip install requests
          python -m pip install tqdm
          python -m pip install bs4
          python -m pip install lxml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run Python Script
        run: |
          python check_data_advalibility.py -parquet

      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "statsbomb/*"
          branches: "main"
          #update_latest_release: true
          overwrite: true
          verbose: true
          default_release_name: "Tracking Data - Parquet"